# Use Python base image
FROM python:3.10-slim

# Install dependencies for dlib
RUN apt-get update && apt-get install -y cmake g++ make

# Set the working directory
WORKDIR /app

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask will run on
EXPOSE 5000

# Start the Flask server
CMD ["python", "app.py"]
